apiVersion: v1
kind: Template
labels:
  template: crda-new-ui
metadata:
  name: crda-new-ui
  annotations:
    description: crda-new-ui
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      service: crda-new-ui
    name: crda-new-ui
  spec:
    selector:
      service: crda-new-ui
    template:
      metadata:
        labels:
          service: crda-new-ui
      spec:
        containers:
        - image: "${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${IMAGE_TAG}"
          name: crda-new-ui
          ports:
          - containerPort: 8080
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
          resources:
            requests:
              memory: 256Mi
              cpu: 250m
            limits:
              memory: 512Mi
              cpu: 500m
        restartPolicy: Always
    test: false
    triggers:
    - type: ConfigChange
    replicas: ${{REPLICAS}}
    strategy:
      rollingParams:
        intervalSeconds: 1
        maxSurge: 0
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      service: crda-new-ui
    name: crda-new-ui
  spec:
    ports:
    - name: "8080"
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      service: crda-new-ui
- apiVersion: v1
  kind: Route
  metadata:
    name: crda-new-ui
  spec:
    to:
      kind: Service
      name: crda-new-ui

parameters:
- description: Docker registry where the image is
  displayName: Docker registry
  required: true
  name: DOCKER_REGISTRY
  value: "quay.io"

- description: Docker image to use
  displayName: Docker image
  required: true
  name: DOCKER_IMAGE
  value: "app-sre/fabric8-analytics-stack-report-ui-revamp"

- description: Image tag
  displayName: Image tag
  required: true
  name: IMAGE_TAG
  value: "latest"

- description: Number of deployment replicas
  displayName: Number of deployment replicas
  required: true
  name: REPLICAS
  value: "1"