apiVersion: v1
kind: Template
labels:
  template: fabric8-analytics-stack-report-ui
metadata:
  name: fabric8-analytics-stack-report-ui
  annotations:
    description: fabric8-analytics-stack-report-ui
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      service: fabric8-analytics-stack-report-ui
    name: fabric8-analytics-stack-report-ui
  spec:
    selector:
      service: fabric8-analytics-stack-report-ui
    template:
      metadata:
        labels:
          service: fabric8-analytics-stack-report-ui
      spec:
        containers:
        - image: "${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${IMAGE_TAG}"
          name: fabric8-analytics-stack-report-ui
          ports:
          - containerPort: 8080
            protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
          resources:
            requests:
              memory: 256Mi
              cpu: 250m
            limits:
              memory: 512Mi
              cpu: 500m
        restartPolicy: Always
    test: false
    triggers:
    - type: ConfigChange
    replicas: ${{REPLICAS}}
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      service: fabric8-analytics-stack-report-ui
    name: fabric8-analytics-stack-report-ui
  spec:
    ports:
    - name: "8080"
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      service: fabric8-analytics-stack-report-ui
- apiVersion: v1
  kind: Route
  metadata:
    name: fabric8-analytics-stack-report-ui
  spec:
    to:
      kind: Service
      name: fabric8-analytics-stack-report-ui

parameters:
- description: Docker registry where the image is
  displayName: Docker registry
  required: true
  name: DOCKER_REGISTRY
  value: "registry.devshift.net"

- description: Docker image to use
  displayName: Docker image
  required: true
  name: DOCKER_IMAGE
  value: "fabric8-analytics-stack-report-ui"

- description: Image tag
  displayName: Image tag
  required: true
  name: IMAGE_TAG
  value: "latest"

- description: Number of deployment replicas
  displayName: Number of deployment replicas
  required: true
  name: REPLICAS
  value: "1"
