name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install
    - run: npm run test:unit
    - run: npm run build:prod
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage/coverage.txt
  openshift-yaml-validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install oc
      uses: redhat-actions/oc-installer@v1
      with:
        oc_version: '4.6'
    - name: Run oc process
      run: oc process --local -f openshift/template.yaml -o yaml > blueprint.yaml
    - name: validate openshift yaml
      uses: instrumenta/kubeval-action@master
      with:
          files: blueprint.yaml
  verify-docker-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install
    - run: npm run build:prod
    - name: Run Docker Build
      run: docker build --no-cache -t tests-image -f Dockerfile .
    
      


  
